name: Run Script

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run update scripts and commit
        run: |
          python imagens.py
          python gt90json.py
          python geraljson.py
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Atualização automática [skip ci]" || echo "Sem alterações"

      - name: Run video
        run: python video.py
        timeout-minutes: 30  # aumenta o tempo para evitar cancelamentos

      - name: Commit video output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Vídeo atualizado [skip ci]" || echo "Sem alterações"
          git push
