name: Run Script

on:
  schedule:
    - cron: "*/30 * * * *" # de 30 em 30 minutos
  workflow_dispatch: # também podes correr manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run script
        run: python imagens.py
          python gt90json.py
          python geraljson.py
          python video.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Atualização automática [skip ci]" || echo "Sem alterações"
          git push
